### ISSUE TITLE
getting error after intalling it through pip3

### ISSUE THREAD

**Issue by imlokisenpai** [yasserbdj96/hiphp#189]
![image](https://user-images.githubusercontent.com/114554103/195613019-44e92003-c89f-4f5e-ad05-7e0924607e20.png)

**Comment by yasserbdj96** [comment]
@imlokisenpai You installed the package, not the program.

-how to use hiphp as a package: https://github.com/yasserbdj96/hiphp#Use-As-Script

-How to use hiphp as a program: https://github.com/yasserbdj96/hiphp#Installation
